#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int umeng_common_gradient_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int umeng_common_gradient_orange = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int umeng_common_gradient_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int umeng_update_btn_check_off_focused_holo_light = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int umeng_update_btn_check_off_holo_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int umeng_update_btn_check_off_pressed_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int umeng_update_btn_check_on_focused_holo_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int umeng_update_btn_check_on_holo_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int umeng_update_btn_check_on_pressed_holo_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int umeng_update_button_cancel_bg_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int umeng_update_button_cancel_bg_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int umeng_update_button_cancel_bg_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int umeng_update_button_cancel_bg_tap = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int umeng_update_button_check_selector = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int umeng_update_button_close_bg_selector = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int umeng_update_button_ok_bg_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int umeng_update_button_ok_bg_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int umeng_update_button_ok_bg_selector = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int umeng_update_button_ok_bg_tap = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int umeng_update_close_bg_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int umeng_update_close_bg_tap = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int umeng_update_dialog_bg = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int umeng_update_title_bg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int umeng_update_wifi_disable = 2130837528;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int MyButton = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int umeng_common_icon_view = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int umeng_common_notification = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int umeng_common_notification_controller = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int umeng_common_progress_bar = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int umeng_common_progress_text = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int umeng_common_rich_notification_cancel = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int umeng_common_rich_notification_continue = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int umeng_common_title = 2131034118;
			
			// aapt resource value: 0x7f05000b
			public const int umeng_update_content = 2131034123;
			
			// aapt resource value: 0x7f05000e
			public const int umeng_update_id_cancel = 2131034126;
			
			// aapt resource value: 0x7f05000c
			public const int umeng_update_id_check = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int umeng_update_id_close = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int umeng_update_id_ignore = 2131034127;
			
			// aapt resource value: 0x7f05000d
			public const int umeng_update_id_ok = 2131034125;
			
			// aapt resource value: 0x7f050009
			public const int umeng_update_wifi_indicator = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int umeng_common_download_notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int umeng_update_dialog = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040019
			public const int UMAppUpdate = 2130968601;
			
			// aapt resource value: 0x7f040011
			public const int UMBreak_Network = 2130968593;
			
			// aapt resource value: 0x7f04001d
			public const int UMDialog_InstallAPK = 2130968605;
			
			// aapt resource value: 0x7f040017
			public const int UMGprsCondition = 2130968599;
			
			// aapt resource value: 0x7f04001b
			public const int UMIgnore = 2130968603;
			
			// aapt resource value: 0x7f040013
			public const int UMNewVersion = 2130968595;
			
			// aapt resource value: 0x7f04001a
			public const int UMNotNow = 2130968602;
			
			// aapt resource value: 0x7f040016
			public const int UMTargetSize = 2130968598;
			
			// aapt resource value: 0x7f04001c
			public const int UMToast_IsUpdating = 2130968604;
			
			// aapt resource value: 0x7f04001e
			public const int UMUpdateCheck = 2130968606;
			
			// aapt resource value: 0x7f040014
			public const int UMUpdateContent = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int UMUpdateNow = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int UMUpdateSize = 2130968597;
			
			// aapt resource value: 0x7f040012
			public const int UMUpdateTitle = 2130968594;
			
			// aapt resource value: 0x7f040006
			public const int umeng_common_action_cancel = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int umeng_common_action_continue = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int umeng_common_action_info_exist = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int umeng_common_action_pause = 2130968580;
			
			// aapt resource value: 0x7f04000c
			public const int umeng_common_download_failed = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int umeng_common_download_finish = 2130968589;
			
			// aapt resource value: 0x7f040007
			public const int umeng_common_download_notification_prefix = 2130968583;
			
			// aapt resource value: 0x7f040010
			public const int umeng_common_icon = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int umeng_common_info_interrupt = 2130968579;
			
			// aapt resource value: 0x7f04000b
			public const int umeng_common_network_break_alert = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int umeng_common_patch_finish = 2130968590;
			
			// aapt resource value: 0x7f040008
			public const int umeng_common_pause_notification_prefix = 2130968584;
			
			// aapt resource value: 0x7f04000f
			public const int umeng_common_silent_download_finish = 2130968591;
			
			// aapt resource value: 0x7f040009
			public const int umeng_common_start_download_notification = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int umeng_common_start_patch_notification = 2130968586;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
